In [2]:
import numpy as np

In [5]:
# x = np.array([1,2,3,4,5,6])
# y = np.array([3,3])

# np.dot(x,y)

In [8]:
a = np.random.rand(5)
a

array([0.14154589, 0.1437614 , 0.98219196, 0.6744902 , 0.82252177])

In [36]:
b = np.random.rand(5,1)
b

array([[0.00781673],
       [0.14564283],
       [0.00771675],
       [0.42123315],
       [0.89317123]])

In [37]:
b.shape

(5, 1)

In [9]:
c = np.random.rand(1,5)
c

array([[0.59291457, 0.7522185 , 0.63580947, 0.8315085 , 0.57755164]])

In [10]:
a.shape

(5,)

In [11]:
b.shape

(5, 1)

In [12]:
c.shape

(1, 5)

In [21]:
a=np.random.randn(3,4) # a.shape = (3, 4)a.shape=(3,4)
b=np.random.randn(1,4) #  b.shape = (1, 4)b.shape=(1,4)
c = a+b
c

array([[ 0.88065964,  0.40717745,  0.21990392,  0.38540561],
       [ 1.86668922, -0.65721008,  1.2613325 , -0.50735874],
       [ 2.98057713,  0.57436155,  1.07535562, -1.18901242]])

In [24]:
a=np.random.randn(1,3) # a.shape = (1, 3)a.shape=(1,3)

b=np.random.randn(3,3) # b.shape = (3, 3)b.shape=(3,3)

c = a*b
c

array([[ 0.14687552,  0.13453283,  0.05741795],
       [-0.05046005, -0.56110656, -0.79036483],
       [ 0.20599782, -0.30034802,  0.39078723]])

In [33]:
a=np.random.randn(12288,150) 

# a.shape = (12288, 150)


b=np.random.randn(150,45) 

# b.shape = (150, 45)

c = np.dot(a,b)

c.shape

(12288, 45)

In [35]:
a=np.random.randn(3,3)

b = np.random.randn(3, 1)

c = a*b
c

array([[ 1.79858769,  1.68443822, -0.82230508],
       [-1.20748095,  1.08212143, -0.90687782],
       [-0.03046124,  0.03136909, -0.03605805]])

In [40]:
a=np.array([[1,1],[1,-1]])

b = np.array([[2], [3]])

c = a + b
c

array([[3, 3],
       [4, 2]])

In [41]:
a=np.random.randn(12288,150) 

# a.shape = (12288, 150)a.shape=(12288,150)

b = np.random.randn(150, 45)

# b.shape = (150, 45)b.shape=(150,45)

c = np.dot(a,b)

c.shape

(12288, 45)

In [43]:
a=np.random.randn(3,4) # a.shape = (3, 4)a.shape=(3,4)

b = np.random.randn(1, 4) #  b.shape = (1, 4)b.shape=(1,4)

c = a + b

c

array([[-0.62851154, -1.48065351, -0.06787848,  2.13505881],
       [-1.47258076, -0.9715575 ,  3.53338625,  1.38299245],
       [-0.15317549, -1.45784513,  0.86257087,  1.39941257]])

In [44]:
x=np.random.randn(8,1)

In [45]:
x.reshape(2,2,2)

array([[[ 0.02255197, -0.70062872],
        [ 0.28084997,  0.82936968]],

       [[ 1.80662514, -0.3162933 ],
        [ 2.73827238, -0.4804077 ]]])

In [46]:
a=np.array([[2,1],[1,3]])

v=np.dot(a,a)
v


array([[ 5,  5],
       [ 5, 10]])

In [58]:
a = np.random.randn(4,3)

b = np.random.randn(4,1)

d = a.T+b
d

ValueError: operands could not be broadcast together with shapes (3,4) (4,1) 

In [57]:
y = np.random.randn(3,3)

i = np.random.randn(3, 1)

o = y*i

o

array([[-0.41238444,  0.45386982, -0.2139343 ],
       [-0.08836927, -2.05246319, -0.66984995],
       [ 1.07056418, -0.1288933 ,  0.7424477 ]])

In [59]:
w = np.zeros((2, 1))
b = np.zeros((1, 2),dtype=int)

In [60]:
w

array([[0.],
       [0.]])

In [61]:
b

array([[0, 0]])

In [65]:
def initialize_with_zeros(dim):
    """
    This function creates a vector of zeros of shape (dim, 1) for w and initializes b to 0.
    
    Argument:
    dim -- size of the w vector we want (or number of parameters in this case)
    
    Returns:
    w -- initialized vector of shape (dim, 1)
    b -- initialized scalar (corresponds to the bias)
    """
    
    ### START CODE HERE ### (≈ 1 line of code)
    w = np.zeros((dim, 1))
    b = float(0)
    ### END CODE HERE ###

    assert(w.shape == (dim, 1))
    assert(isinstance(b, float) or isinstance(b, int))
    
    return w, b

In [66]:
dim = 2
w, b = initialize_with_zeros(dim)
print(type(b))
assert type(b) == float
print ("w = " + str(w))
print ("b = " + str(b))

<class 'float'>
w = [[0.]
 [0.]]
b = 0.0


In [80]:
# GRADED FUNCTION: propagate

def propagate(w, b, X, Y):
    """
    Implement the cost function and its gradient for the propagation explained above

    Arguments:
    w -- weights, a numpy array of size (num_px * num_px * 3, 1)
    b -- bias, a scalar
    X -- data of size (num_px * num_px * 3, number of examples)
    Y -- true "label" vector (containing 0 if non-cat, 1 if cat) of size (1, number of examples)

    Return:
    cost -- negative log-likelihood cost for logistic regression
    dw -- gradient of the loss with respect to w, thus same shape as w
    db -- gradient of the loss with respect to b, thus same shape as b
    
    Tips:
    - Write your code step by step for the propagation. np.log(), np.dot()
    """
    
    m = X.shape[1]
    
    # FORWARD PROPAGATION (FROM X TO COST)
    #(≈ 2 lines of code)
    # compute activation
    # A = ...
    # compute cost by using np.dot to perform multiplication. 
    # And don't use loops for the sum.
    # cost = ...                                
    # YOUR CODE STARTS HERE
    A=(w*X+b)
    cost=(1/m)*sum((Y*np.log(A))+(1-Y)*np.log(1-A))
    # YOUR CODE ENDS HERE

    # BACKWARD PROPAGATION (TO FIND GRAD)
    #(≈ 2 lines of code)
    # dw = ...
    # db = ...
    # YOUR CODE STARTS HERE
    dw=(X/m)*((A-Y))
    db=1/m*sum(A-Y)
    # YOUR CODE ENDS HERE
    cost = np.squeeze(np.array(cost))

    
    grads = {"dw": dw,
             "db": db}
    
    return grads, cost

In [81]:
w =  np.array([[1.], [2]])
b = 1.5
X = np.array([[1., -2., -1.], [3., 0.5, -3.2]])
Y = np.array([[1, 1, 0]])
#https://towardsdatascience.com/logistic-regression-detailed-overview-46c4da4303bc

In [79]:
w*X

array([[ 1. , -2. , -1. ],
       [ 6. ,  1. , -6.4]])

In [87]:

grads, cost = propagate(w, b, X, Y)
grads["dw"].shape
assert type(grads["dw"]) == np.ndarray
# assert grads["dw"].shape == (2, 1)
# assert type(grads["db"]) == np.float64


print ("dw = " + str(grads["dw"]))
print ("db = " + str(grads["db"]))
print ("cost = " + str(cost))



dw = [[ 0.5         1.         -0.16666667]
 [ 6.5         0.25        5.22666667]]
db = [ 2.66666667  0.         -1.46666667]
cost = [nan nan nan]


c:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:33: RuntimeWarning: invalid value encountered in log
